Repository Tabeyouka/tabeyouka-backend, pull requests merged in 2023-06, with the labels that each got.

#63 Modify routing path, add seed file and fix error handling
  app/Http/Controllers/LocalSemesterCommentsController.php
  app/Http/Controllers/LocalSemesterController.php
  database/factories/LocalSemesterFactory.php
  database/seeders/LocalSemesterSeeder.php
  routes/api.php
  tests/Feature/LocalSemesterCommentsTest.php
Labels: 🔨 Refactor, 🐞 BugFix, 📬 API

#64 Modify routing path, add seed file and fix error handling #63
  app/Http/Controllers/LocalSemesterCommentsController.php
  app/Http/Controllers/LocalSemesterController.php
  database/factories/LocalSemesterFactory.php
  database/seeders/LocalSemesterSeeder.php
  routes/api.php
  tests/Feature/LocalSemesterCommentsTest.php
Labels: 🔨 Refactor, 🐞 BugFix, 📬 API

#66 🎨 refactor : Refactor image url
  parse_restaurants.php
  routes/api.php
Labels: 🔨 Refactor, 📬 API

#67 🎨 refactor : Refactor image url & Get restaurant information
  app/Http/Controllers/ReviewController.php
  app/Http/Kernel.php
  app/Http/Middleware/ValidateAddReview.php
  app/Http/Middleware/ValidateEditReview.php
  database/factories/ReviewFactory.php
  parse_restaurants.php
  routes/api.php
  tests/Feature/LocalSemesterCommentsTest.php
  tests/Feature/ReviewControllerTest.php
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#69 🔨 chore : Upload teammates images
  public/images/teammates/hyeon.jpeg
  public/images/teammates/hyunjun.jpg
  public/images/teammates/jeongwon.png
  public/images/teammates/seongjun.png
  public/images/teammates/youngjin.jpg
  public/images/teammates/yumin.png
Labels: 🌏 Deploy

#70 🔨 chore : Upload teammates images
  public/images/teammates/hyeon.jpeg
  public/images/teammates/hyunjun.jpg
  public/images/teammates/jeongwon.png
  public/images/teammates/seongjun.png
  public/images/teammates/youngjin.jpg
  public/images/teammates/yumin.png
Labels: 🌏 Deploy

#72 🐛 fix : Modify TeammateController routes
  routes/api.php
Labels: 🐞 BugFix, 📬 API

#73 🐛 fix : Modify TeammateController routes
  routes/api.php
Labels: 🐞 BugFix, 📬 API

#77 fix: Add exception handling
  app/Http/Controllers/ReviewController.php
Labels: 🐞 BugFix

#78 🐛 fix: Add exception handling
  app/Http/Controllers/ReviewController.php
Labels: 🔨 Refactor

#80 🎨 refactor : Refactor image routes
  app/Http/Controllers/CommunityController.php
Labels: 🔨 Refactor

#82 🐛 fix : Fix CORS error & Refactor : Modify teammates image routes
  app/Http/Kernel.php
  app/Http/Middleware/HandleCors.php
  public/.htaccess
  public/images/hyeon.jpeg
  public/images/hyunjun.jpg
  public/images/jeongwon.png
  public/images/seongjun.png
  public/images/youngjin.jpg
  public/index.php
  storage/app/public/.gitignore
Labels: 🔨 Refactor, 🐞 BugFix

#81 🎨 refactor : Refactor image routes
  app/Http/Controllers/CommunityController.php
  app/Http/Kernel.php
  app/Http/Middleware/HandleCors.php
  public/.htaccess
  public/images/hyeon.jpeg
  public/images/hyunjun.jpg
  public/images/jeongwon.png
  public/images/seongjun.png
  public/images/youngjin.jpg
  public/index.php
  storage/app/public/.gitignore
Labels: 🔨 Refactor

#84 ✨ feat : Embody RefreshToken feature
  app/Http/Controllers/UserController.php
  composer.json
  composer.lock
  config/jwt.php
  routes/api.php
  tests/Feature/UserControllerTest.php
Labels: ✨ Feature, ✅ Test

#85 ✨ feat : Embody RefreshToken feature
  app/Http/Controllers/UserController.php
  composer.json
  composer.lock
  config/jwt.php
  routes/api.php
  tests/Feature/UserControllerTest.php
Labels: ✨ Feature, ✅ Test

#87 🐛 fix : Fix JWT logic
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: 🔨 Refactor, 🐞 BugFix, 📬 API

#88 🐛 fix : Fix JWT logic
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: 🔨 Refactor, 🐞 BugFix, 📬 API

#89 🎨 refactor : Change to session authentication
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: 🔨 Refactor, 📬 API

#90 🎨 refactor : Change to session authentication
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: 🔨 Refactor, 📬 API

#92 🎨 refactor : Modify class name
  app/Http/Middleware/ValidateEmpty.php
  routes/api.php
Labels: 🔨 Refactor

#93 ✨ feat : Add seed file
  database/seeders/DatabaseSeeder.php
Labels: ⚙ Setting

#96 🔨 chore : Exclude All from CSRF verification
  app/Http/Middleware/VerifyCsrfToken.php
Labels: 🥰 Accessibility

#97 ✨ feat : Create Get Users information API
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#98 ✨ feat : Create Get Users information API
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#99 🐛 fix : Modify logic to return Teammate id
  app/Http/Controllers/TeammateController.php
Labels: 🐞 BugFix

#100 🐛 fix : Modify logic to return Teammate id
  app/Http/Controllers/TeammateController.php
Labels: 🐞 BugFix

#101 🎨 refactor : Activate middleware code
  app/Http/Controllers/CommunityController.php
  routes/api.php
Labels: 🔨 Refactor, 📬 API

#103 🎨 refactor : Modify Posts response form & Activate middleware code
  app/Http/Controllers/CommunityController.php
  routes/api.php
Labels: 🔨 Refactor, 📬 API

#104 🎨 refactor : Modify misspelling
  app/Http/Controllers/CommunityController.php
Labels: 🔨 Refactor, 🐞 BugFix

#105 🎨 refactor : Modify misspelling
  app/Http/Controllers/CommunityController.php
Labels: 🔨 Refactor, 🐞 BugFix

#106 🐛 fix : Fix Login error
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#107 🐛 fix : Fix Login error
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#108 🎨 refactor : Modify teammate return json form
  app/Http/Controllers/TeammateController.php
Labels: 🔨 Refactor, 📬 API

#111 ✨ feat : Create Get Login status logic
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#112 ✨ feat : Create Get Login Status logic
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#113 ✨ feat : Create Get Login Status logic
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#115 🐛 fix : Change image storage address
  .env.example
  app/Http/Controllers/CommunityController.php
  app/Http/Controllers/TeammateController.php
Labels: 🔨 Refactor, 🐞 BugFix

#116 🔨 chore : Update project
  app/Http/Kernel.php
  composer.json
  composer.lock
  routes/api.php
Labels: ⚙ Setting

#118 ✨ feat: Implement session login logic
  app/Http/Controllers/UserController.php
  app/Http/Middleware/EncryptCookies.php
  config/session.php
  database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
Labels: ✨ Feature, 📬 API

#120 🎨 refactor : Remove unnecessary syntax
  app/Http/Controllers/CommunityController.php
Labels: 🔨 Refactor

#121 🎨 refactor : Remove unnecessary syntax
  app/Http/Controllers/CommunityController.php
Labels: 🔨 Refactor

#122 🎨 refactor : Modify return data
  app/Http/Controllers/TeammateController.php
Labels: 🔨 Refactor, 📬 API

#124 🎨 refactor : Modify validate elements, getAuthenticatedUser & getLoginStatus method
  app/Http/Controllers/TeammateController.php
  app/Http/Controllers/UserController.php
Labels: 🔨 Refactor, 📬 API

#125 🎨 refactor : Modify validate elements, getAuthenticatedUser & getLoginStatus method
  app/Http/Controllers/TeammateController.php
  app/Http/Controllers/UserController.php
Labels: 🔨 Refactor, 📬 API

#126 🎨 refactor : Modify image_file to image
  app/Models/Community.php
Labels: 🔨 Refactor

#127 🎨 refactor : Modify image_file to image
  app/Models/Community.php
Labels: 🔨 Refactor

#128 🐛 fix : Fix store method error correction & 🎨 refactor : Add Exception Handling
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/CommunityController.php
  app/Http/Controllers/LocalSemesterCommentsController.php
Labels: 🔨 Refactor, 🐞 BugFix, 📬 API

#129 🐛 fix : Fix store method error correction & 🎨 refactor : Add Exception Handling
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/CommunityController.php
  app/Http/Controllers/LocalSemesterCommentsController.php
Labels: 🔨 Refactor, 🐞 BugFix, 📬 API

#130 🐛 fix : Fix update method error
  app/Http/Controllers/TeammateController.php
Labels: 🐞 BugFix

#132 🎨 refactor : Modify image saving path
  app/Http/Controllers/ReviewController.php
Labels: 🔨 Refactor

#133 🎨 refactor : Modify image saving path
  app/Http/Controllers/ReviewController.php
Labels: 🔨 Refactor

#134 🔨 chore : Remove validation logic
  app/Http/Controllers/ReviewController.php
Labels: 🔨 Refactor

#137 🔨 chore : Commit Temporary files
  app/Http/Controllers/CommunityController.php
  app/Providers/RouteServiceProvider.php
  routes/api.php
Labels: 🔨 Refactor

#138 📝 docs : Create migration file
  app/Http/Controllers/ReviewController.php
  database/migrations/2023_06_14_135835_add_master_column_for_users_table.php
Labels: ✨ Feature

#139 📝 docs : Create migration file
  app/Http/Controllers/ReviewController.php
  database/migrations/2023_06_14_135835_add_master_column_for_users_table.php
Labels: ✨ Feature

#141 🎨 refactor : Add author_id column
  app/Http/Controllers/CommunityController.php
  app/Http/Kernel.php
Labels: 🔨 Refactor

#142 🎨 refactor : Modify logic for add nickname column
  app/Http/Controllers/CommunityController.php
  app/Models/Community.php
  database/migrations/2023_06_15_052228_add_nickname_to_communities_table.php
Labels: 🔨 Refactor

#143 🎨 refactor : Modify logic for add nickname column
  app/Http/Controllers/CommunityController.php
  app/Models/Community.php
  database/migrations/2023_06_15_052228_add_nickname_to_communities_table.php
Labels: 🔨 Refactor

#144 🎨 refactor : Remove unnecessary comments
  app/Http/Controllers/CommunityController.php
Labels: 🔨 Refactor

#145 🎨 refactor : Modify to return the restaurant ID
  app/Http/Controllers/CommunityController.php
  app/Http/Controllers/RestaurantController.php
Labels: 🔨 Refactor, 📬 API

#146 🎨 refactor : Add nickname column to local_semester_comments table
  app/Http/Controllers/RestaurantController.php
  database/migrations/2023_06_15_085800_add_nickname_to_local_semester_comments_table.php
Labels: 🔨 Refactor

#147 🎨 refactor : Add nickname column to local_semester_comments table
  database/migrations/2023_06_15_085800_add_nickname_to_local_semester_comments_table.php
Labels: 🔨 Refactor

#148 ✨ feat : add nickname column at reviews table
  app/Http/Controllers/LocalSemesterCommentsController.php
  app/Http/Controllers/ReviewController.php
  app/Models/LocalSemesterComments.php
  app/Models/Review.php
  database/migrations/2023_06_15_100207_add_nickname_to_reviews_table.php
Labels: ✨ Feature

#149 ✨ feat : add nickname column at reviews table
  app/Http/Controllers/LocalSemesterCommentsController.php
  app/Http/Controllers/ReviewController.php
  app/Models/LocalSemesterComments.php
  app/Models/Review.php
  database/migrations/2023_06_15_100207_add_nickname_to_reviews_table.php
Labels: ✨ Feature

#151 🎨 refactor : Remove unnecessary comments
  app/Http/Controllers/LocalSemesterCommentsController.php
  app/Http/Controllers/ReviewController.php
  app/Http/Controllers/UserController.php
  app/Models/LocalSemesterComments.php
  routes/api.php
Labels: 🔨 Refactor

#154 🎨 refactor : Remove unused logic
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: 🔨 Refactor

#155 ✅ test : Fix test code errors
  app/Http/Controllers/ReviewController.php
  app/Http/Middleware/ValidateEmpty.php
  database/factories/ReviewFactory.php
  tests/Feature/ReviewControllerTest.php
  tests/Unit/TeammateControllerTest.php
Labels: ✅ Test

#156 ✅ test : Fix test code errors
  app/Http/Controllers/ReviewController.php
  app/Http/Middleware/ValidateEmpty.php
  database/factories/ReviewFactory.php
  tests/Feature/ReviewControllerTest.php
  tests/Unit/TeammateControllerTest.php
Labels: ✅ Test

#157 ✅ test : Fix local semester comments test code errors
  app/Http/Controllers/LocalSemesterCommentsController.php
  database/factories/LocalSemesterCommentsFactory.php
  tests/Feature/LocalSemesterCommentsTest.php
Labels: 🐞 BugFix, ✅ Test

#159 🐛 fix : Fix update comment api
  routes/api.php
Labels: 🐞 BugFix, 📬 API

#160 🐛 fix : Fix update comment api
  routes/api.php
Labels: 🐞 BugFix, 📬 API

#161 🎨 refactor : Remove unnecessary comments
  app/Http/Controllers/UserController.php
Labels: 🔨 Refactor

#162 🎨 refactor : Remove unnecessary comments
  app/Http/Controllers/UserController.php
Labels: 🔨 Refactor

#163 🎨 refactor : Remove validation logic
  app/Http/Controllers/ReviewController.php
Labels: 🔨 Refactor

#164 🎨 refactor : Remove validation logic
  app/Http/Controllers/ReviewController.php
Labels: 🔨 Refactor

#165 🐛 fix : Fix Review Controller logic
  app/Http/Controllers/ReviewController.php
  app/Models/Review.php
  tests/Unit/TeammateControllerTest.php
Labels: 🐞 BugFix

#166 🐛 fix : Fix Review Controller logic
  app/Http/Controllers/ReviewController.php
  app/Models/Review.php
  tests/Unit/TeammateControllerTest.php
Labels: 🐞 BugFix

#167 🐛 fix : Fix review controller
  app/Http/Controllers/ReviewController.php
Labels: 🐞 BugFix

#168 🐛 fix : Fix review controller
  app/Http/Controllers/ReviewController.php
Labels: 🐞 BugFix

#169 🐛 fix : Modify image path
  app/Http/Controllers/ReviewController.php
Labels: 🐞 BugFix

#170 🐛 fix : Modify image path
  app/Http/Controllers/ReviewController.php
Labels: 🐞 BugFix

#171 🐛 fix : Modify image path and remove validation logic
  app/Http/Controllers/ReviewController.php
Labels: 🐞 BugFix

#172 🐛 fix : Modify image path and remove validation logic
  app/Http/Controllers/ReviewController.php
Labels: 🐞 BugFix

#173 🔨 chore : Add rows when fetching data
  app/Http/Controllers/RestaurantController.php
Labels: 🔨 Refactor

#174 🔨 chore : Add rows when fetching data
  app/Http/Controllers/RestaurantController.php
Labels: 🔨 Refactor

#175 🎨 refactor : Add nickname column to comments table & Modify CommentController logic
  app/Http/Controllers/CommentController.php
  database/migrations/2023_06_17_053513_add_nickname_to_comments_table.php
Labels: 🔨 Refactor

#176 🎨 refactor : Add nickname column to comments table & Modify CommentController logic
  app/Http/Controllers/CommentController.php
  database/migrations/2023_06_17_053513_add_nickname_to_comments_table.php
Labels: 🔨 Refactor

#177 🎨 refactor : Modify update logic & Add comments
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/UserController.php
Labels: 🔨 Refactor

#178 🎨 refactor : Modify update logic & Add comments
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/UserController.php
Labels: 🔨 Refactor

#179 🎨 refactor : Modify comment logic & Remove unnecessary comments
  app/Http/Controllers/CommentController.php
  routes/api.php
Labels: 🔨 Refactor, 🐞 BugFix

#180 🎨 refactor : Modify comment logic & Remove unnecessary comments
  app/Http/Controllers/CommentController.php
  routes/api.php
Labels: 🔨 Refactor, 🐞 BugFix

#181 🐛 fix : Fix nickname error
  app/Http/Controllers/CommentController.php
  app/Models/Comment.php
Labels: 🐞 BugFix

#182 🐛 fix : Fix nickname error
  app/Http/Controllers/CommentController.php
  app/Models/Comment.php
Labels: 🐞 BugFix

#183 🐛 fix : Fix update, destroy method error
  app/Http/Controllers/CommentController.php
Labels: 🐞 BugFix
